main_app/urls.py
from django.urls import path
# the '.' represent that we are on the same file line, like a sibling file
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('travels/', views.travels_index, name='index'),
    path('travels/<int:travel_id>/', views.travels_detail, name='detail'),
    path('travels/create/', views.TravelCreate.as_view(), name='travels_create'),
    path('travels/<int:pk>/update/', views.TravelUpdate.as_view(), name='travels_update'),
    path('travels/<int:pk>/delete/', views.TravelDelete.as_view(), name='travels_delete'),
    path('travels/<int:travel_id>/add_review/', views.add_review, name='add_review'),
    path('tags/', views.tags_index, name='tags_index'),
    path('tags/<int:tag_id>/', views.tags_detail, name='tags_detail'),
    path('tags/create/', views.TagCreate.as_view(), name='tags_create'),
    path('tags/<int:pk>/update/', views.TagUpdate.as_view(), name='tags_update'),
    path('tags/<int:pk>/delete/', views.TagDelete.as_view(), name='tags_delete'),
    path('travels/<int:travel_id>/assoc_tag/<int:tag_id>/', views.assoc_tag, name='assoc_tag'),
]

travelcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/models.py
from django.urls import reverse
from django.db import models
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator

# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tags_detail', kwargs={'tag_id': self.id})

class Travel(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    rating = models.PositiveIntegerField(
        default=0,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ]
    )
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'travel_id': self.id})

class Reviews(models.Model):
    review = models.TextField(max_length=300)
    name = models.CharField(max_length=100)
    
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE)

    def __str__(self):
        return self.review

main_app/forms.py
from django.forms import ModelForm
from .models import Reviews

class ReviewsForm(ModelForm):
  class Meta:
    model = Reviews
    fields = ['name', 'review']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from . models import Travel, Tag
from .forms import ReviewsForm



# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def travels_index(request):
    travels = Travel.objects.all()
    return render(request, 'travels/index.html', { 'travels': travels })

def travels_detail(request, travel_id):
    travel = Travel.objects.get(id=travel_id)
    id_list = travel.tags.all().values_list('id')
    travel_tags_doesnt_have = Tag.objects.exclude(id__in=id_list)
    review_form = ReviewsForm()
    return render(request, 'travels/detail.html', {
        'travel': travel, 'review_form': review_form,
        'tags': travel_tags_doesnt_have
    })
    
def assoc_tag(request, travel_id, tag_id):
    Travel.objects.get(id=travel_id).tags.add(tag_id)
    return redirect('detail', travel_id=travel_id)

def add_review(request, travel_id):
    form = ReviewsForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.travel_id = travel_id
        new_review.save()
    return redirect('detail', travel_id=travel_id)

def tags_index(request):
    tags = Tag.objects.all()
    return render(request, 'tags/index.html', { 'tags': tags })

def tags_detail(request, tag_id):
    tag = Tag.objects.get(id=tag_id)
    return render(request, 'tags/detail.html', { 'tag': tag })

# class TravelList(ListView):
#     model = Travel

class TravelCreate(CreateView):
    model = Travel
    fields = '__all__'
    success_url = '/travels/'

class TravelUpdate(UpdateView):
    model = Travel
    fields = '__all__'

class TravelDelete(DeleteView):
    model = Travel
    success_url = '/travels/'

class TagCreate(CreateView):
    model = Tag
    fields = '__all__'
    success_url = '/tags/'

class TagUpdate(UpdateView):
    model = Tag
    fields = '__all__'

class TagDelete(DeleteView):
    model = Tag
    success_url = '/tags/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Travel Collector </h1>
<hr />
<p>The world is your oyster</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Travel Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo"
                >&nbsp;&nbsp;TravelCollector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'tags_index' %}">View All Tags</a></li>
            <li><a href="{% url 'tags_create' %}">Create a Tag</a></li>
            <li><a href="{% url 'travels_create' %}">Create Travel</a></li>
            <li><a href="{%  url 'index' %}">View All My Travels</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2022 Travel Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home Already?</h1>

{% endblock %}

main_app/templates/main_app/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tag</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ tag.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' tag.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tag_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
  <h1>Edit <span class="teal-text">{{object.title}}</span> Tag</h1>
  {% else %}
  <h1>Create a Tag</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/travel_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Travel</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ travel.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' travel.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/travel_form.html
{% extends 'base.html' %}

{% block content %}
  {% if travel %}
    <h1>Edit Travel</h1>
  {% else %}
    <h1>Add Travel</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/travels/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Travel Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ travel.title }}</span>
        <p>Location: {{ travel.location }}</p>
        <p>Description: {{ travel.description }}</p>
        <p>Rating: {{ travel.rating }}/10</p>
      </div>
      <div class="card-action">
        <a href="{% url 'travels_update' travel.id %}">Edit</a>
        <a href="{% url 'travels_delete' travel.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_review' travel.id %}" method="POST">
      {% csrf_token %} {{ review_form.as_p }}
      <input type="submit" class="btn" value="Add Review" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Reviews</th>
        </tr>
      </thead>
      <tbody>
        {% for reviews in travel.reviews_set.all %}
        <tr>
          <td>{{reviews.name}}</td>
          <td>{{reviews.review}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>Descriptive tags for {{ travel.title }}</h3>
    {% if travel.tags.count %} {% for tag in travel.tags.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ tag.title }} </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Tags :(</h5>
    {% endif %}
  </div>
  <!-- Available tag will come after this line -->
  <div class="col s6">
    <h3>Available Tags</h3>
    {% if tags.count %} {% for tag in tags.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{tag.title }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_tag' travel.id tag.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{travel.title}} Available Tag</h5>
    {% endif %}
  </div>
  {% endblock %}
</div>

main_app/templates/travels/index.html
{% extends 'base.html' %} 

{% block content %}

<h1>Travel List</h1>

{% for travel in travels %}
<div class="card">
  <a href="{% url 'detail' travel.id %}">
    <div class="card-content">
      <span class="card-title">{{ travel.title }}</span>
      <p>Location: {{ travel.location }}</p>
      <p>Description: {{ travel.description }}</p>
      <p>Rating: {{ travel.rating }}/10</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}